behaviors:
  DobotCR16:
    trainer_type: ppo
    max_steps: 1e7
    time_horizon: 100
    threaded: True
    hyperparameters:
      # common
      learning_rate: 0.0002
      batch_size: 2048
      buffer_size: 10240
      learning_rate_schedule: linear
      # specific
      beta: 0.005
      epsilon: 0.2
      beta_schedule: linear
      epsilon_schedule: linear
      lambd: 0.97
      num_epoch: 4
      shared_critic: False
    network_settings:
      # common
      hidden_units: 512
      num_layers: 3
      normalize: False
      vis_encode_type: simple
      conditioning_type: None
      # specific
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.995
