behaviors:
  DobotCR16:
    trainer_type: ppo
    keep_checkpoints: 5
    max_steps: 200000
    time_horizon: 1000
    summary_freq: 50000
    threaded: true
    hyperparameters:
      batch_size: 128
      beta: 1.0e-3
      buffer_size: 10240
      epsilon: 0.1
      lambd: 0.95
      learning_rate: 1.0e-4
      learning_rate_schedule: linear
      num_epoch: 3
    network_settings:
      hidden_units: 128
      normalize: true
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
